language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  skip-cleanup: true
  # Deployment source
  local-dir: build
  project-name: forkdelta/nextgen-ui
  on:
    repo: forkdelta/nextgen-ui
    branch: master
  # Deployment target
  repo: forkdelta/next
  target-branch: master
  keep-history: true
